"""initial schema

Revision ID: 5a5493e23e56
Revises: 
Create Date: 2026-09-11 19:05:19.847041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a5493e23e56'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('notificacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('destinatario_email', sa.String(length=255), nullable=False),
    sa.Column('assunto', sa.String(length=500), nullable=False),
    sa.Column('corpo', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('enviado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('entregue', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.String(length=20), nullable=False),
    sa.Column('area_id', sa.UUID(), nullable=True),
    sa.Column('senha_provisoria', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('bases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('area_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=500), nullable=False),
    sa.Column('status_atual', sa.String(length=20), nullable=False),
    sa.Column('criado_por', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs_auditoria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entidade', sa.String(length=50), nullable=False),
    sa.Column('entidade_id', sa.UUID(), nullable=False),
    sa.Column('acao', sa.String(length=100), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('detalhes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_table('links_publicacao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('base_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('gerado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('gerado_por', sa.UUID(), nullable=False),
    sa.Column('enviado_ao_portal', sa.Boolean(), nullable=False),
    sa.Column('enviado_ao_portal_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enviado_ao_portal_por', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['base_id'], ['bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enviado_ao_portal_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['gerado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_id')
    )
    op.create_index(op.f('ix_links_publicacao_token'), 'links_publicacao', ['token'], unique=True)
    op.create_table('versoes_base',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('base_id', sa.UUID(), nullable=False),
    sa.Column('numero_versao', sa.Integer(), nullable=False),
    sa.Column('dados_formulario', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enviado_por', sa.UUID(), nullable=False),
    sa.Column('enviado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('analisado_por', sa.UUID(), nullable=True),
    sa.Column('analisado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_rejeicao_categoria', sa.String(length=50), nullable=True),
    sa.Column('motivo_rejeicao_detalhe', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analisado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['base_id'], ['bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enviado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arquivos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('versao_base_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('nome_original', sa.String(length=500), nullable=False),
    sa.Column('caminho_armazenamento', sa.String(length=1000), nullable=False),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('enviado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['versao_base_id'], ['versoes_base.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arquivos')
    op.drop_table('versoes_base')
    op.drop_index(op.f('ix_links_publicacao_token'), table_name='links_publicacao')
    op.drop_table('links_publicacao')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_table('logs_auditoria')
    op.drop_table('bases')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('notificacoes')
    op.drop_table('areas')
    # ### end Alembic commands ###
